spring:
  application:
    name: MailSender
  mandatory-file-encoding: utf-8

  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:./src/main/resources/database/EmbeddedDb;INIT=create schema if not exists ADDRESSEES\; runscript from './src/main/resources/database/create-db.sql'
    #jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        hibernate:
#          jdbc:
#            lob:
#              non_contextual_creation: true



  mail:
    host: smtp.gmail.com
    username: 1Adeptus.Mechanicus1@gmail.com
    password: 28301230aaMP
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  debug: true

server:
  port: 8089