spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Paleontolog/MailSender.git
#          searchPaths: "/src/main/resources"


  application:
    name: MailSender


  mustache:
    prefix: classpath:/templates/
    suffix: .html

#  mandatory-file-encoding: UTF-8

  # ===============================
  # DB
  # ===============================

#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: mail

#  datasource:
#    url: jdbc:h2:./src/main/resources/database/EmbeddedDb;INIT=create schema if not exists ADDRESSEES\; runscript from './src/main/resources/database/create-db.sql'
#    #url: jdbc:h2:tcp://localhost/~/test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
  # ===============================
  # JPA / HIBERNATE
  # ===============================
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    username: 1Adeptus.Mechanicus1@gmail.com
    password: 28301230aaMP
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  debug: true

server:
  port: 8080

schedule:
  url: https://data.gov.ru/opendata/7708660670-proizvcalendar
  cron: "0 0 17 * * MON-FRI"
  #cron: "*/5 * * * * MON-FRI"


